### ISSUE TITLE
第57回 dorachan1029, pupupopo88, ta1kt0me

### ISSUE THREAD

**Issue by dorachan1029** [yochiyochirb/meetups#867]
5.3.2 「Railsのルート」から

http://railstutorial.jp/chapters/filling-in-the-layout?version=4.0#sec-rails_routes

**Comment by ta1kt0me** [comment]
> matchを利用する方がよりRailsの慣例に従っています

へー

**Comment by ta1kt0me** [comment]
before

> static_pages_help GET /static_pages/help(.:format)  static_pages#help

after

> help GET /help(.:format)               static_pages#help

**Comment by pupupopo88** [comment]
これっていつ使うんだろう
> URL変えたくなった時、パスをいろんなところで使いたくなった時

**Comment by ta1kt0me** [comment]
get だとできないのかなぁ
```
get "static_pages/help", as: :help 
# => help GET /static_pages/help(.:format)  static_pages#help
```

**Comment by dorachan1029** [comment]
> なお、Railsチュートリアルでは、path書式を使用する一般的な規約に従い、リダイレクトの場合のみurl書式を使用します。

なるべく変数を使った方がいいんですね！

**Comment by ta1kt0me** [comment]
path書式

忘れがち

**Comment by ta1kt0me** [comment]
> URLヘルパー

ってなんでしたっけ？

**Comment by dorachan1029** [comment]
どのファイルだ！？

**Comment by ta1kt0me** [comment]
勘違いしてた

**Comment by ta1kt0me** [comment]
テスト実行したら落ちたので直さないといけない....

**Comment by ta1kt0me** [comment]
http://qiita.com/snaka/items/eeb5dee96e44fca54a2e

> app.root_url
# => "http://www.example.com/"

rails console で確認できた！

**Comment by dorachan1029** [comment]
URLヘルパー　＝　名前付きルート

**Comment by ta1kt0me** [comment]
brace 使うときに 半角スペース入れる？入れない？

**Comment by yucao24hours** [comment]
そろそろです〜

**Comment by ta1kt0me** [comment]
subject を複数定義できるか

**Comment by ta1kt0me** [comment]
```rb
  subject(:hoge) { page }
  subject(:fuga) { page }

  describe "Home page" do
    before { visit root_path }

    it { expect(hoge).to have_content('Sample App') }
    it { expect(fuga).to have_title("Ruby on Rails Tutorial Sample App") }
    it { should_not have_title('| Home') }
  end
```

**Comment by ta1kt0me** [comment]
subjectを省略した場合、後勝ちするっぽい

```rb
  subject(:hoge) { page }
  subject(:fuga) { 'page' }

  describe "Home page" do
    before { visit root_path }

    it { fuga.should have_content('Sample App') }
    it { hoge.should have_title("Ruby on Rails Tutorial Sample App") }
    it { should_not have_title('| Home') }
  end
```

```sh
21:39:18[sample_app_ycyc]$ be rspec spec/requests/static_pages_spec.rb:8                                                                                *[filling-in-ayout][2.0.0-p481]
No DRb server is running. Running in local process instead ...
Run options: include {:locations=>{"./spec/requests/static_pages_spec.rb"=>[8]}}
F.F

Failures:

  1) Static Pages Home page
     Failure/Error: it { fuga.should have_content('Sample App') }
     NoMethodError:
       undefined method `has_content?' for "aaa":String
     # ./spec/requests/static_pages_spec.rb:11:in `block (3 levels) in <top (required)>'

  2) Static Pages Home page
     Failure/Error: it { should_not have_title('| Home') }
     NoMethodError:
       undefined method `has_title?' for "aaa":String
     # ./spec/requests/static_pages_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 0.0524 seconds
3 examples, 2 failures

Failed examples:

rspec ./spec/requests/static_pages_spec.rb:11 # Static Pages Home page
rspec ./spec/requests/static_pages_spec.rb:13 # Static Pages Home page

Randomized with seed 8438
```

```rb
  subject(:hoge) { 'aaa' }
  subject(:fuga) { page }

  describe "Home page" do
    before { visit root_path }

    it { fuga.should have_content('Sample App') }
    it { hoge.should have_title("Ruby on Rails Tutorial Sample App") }
    it { should_not have_title('| Home') }
  end
```



```sh
21:39:49[sample_app_ycyc]$ be rspec spec/requests/static_pages_spec.rb:8                                                                                *[filling-in-ayout][2.0.0-p481]
No DRb server is running. Running in local process instead ...
Run options: include {:locations=>{"./spec/requests/static_pages_spec.rb"=>[8]}}
F..

Failures:

  1) Static Pages Home page
     Failure/Error: it { hoge.should have_title("Ruby on Rails Tutorial Sample App") }
     NoMethodError:
       undefined method `has_title?' for "aaa":String
     # ./spec/requests/static_pages_spec.rb:12:in `block (3 levels) in <top (required)>'

Finished in 0.0576 seconds
3 examples, 1 failure

Failed examples:

rspec ./spec/requests/static_pages_spec.rb:12 # Static Pages Home page


```

**Comment by pupupopo88** [comment]
5.3.4 の
```
subject { page }
```
くらいまで終わりました

**Comment by pupupopo88** [comment]
使えはするけれど、実際は使わないよねというお話に
