### ISSUE TITLE
第63回 @hashcc @yutackall @ta1kt0me

### ISSUE THREAD

**Issue by ta1kt0me** [yochiyochirb/meetups#946]
6.1.4ユーザーオブジェクトを検索するからいきまーす！

**Comment by ta1kt0me** [comment]
findメソッドは例外 (exception) を発生させる

**Comment by ta1kt0me** [comment]
find_byはデータない時に、nilが返ってくる

**Comment by ta1kt0me** [comment]
```
>User.find(1,2)
=> [#<User id: 1, name: nil, email: nil, created_at: "2015-04-06 11:58:39", updated_at: "2015-04-06 11:58:39">, #<User id: 2, name: nil, email: nil, created_at: "2015-04-06 11:58:40", updated_at: "2015-04-06 11:58:40">]
```
findにidを配列で渡すと、結果のActiveRecordオブジェクトが配列で返ってくる。

**Comment by ta1kt0me** [comment]
find_byで服数レコードがマッチする条件を指定すると、1件だけ返ってくる。
`LIMIT 1`に注目。
```ruby
irb(main):021:0> User.find_by(email: "foo@bar.com")
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" = 'foo@bar.com' LIMIT 1
=> #<User id: 6, name: "Foo", email: "foo@bar.com", created_at: "2015-04-06 12:00:30", updated_at: "2015-04-06 12:00:30">
```

**Comment by ta1kt0me** [comment]
all, first,last,countとか、よく使うよねー

**Comment by ta1kt0me** [comment]
`find_by!`で例外発生！
```
User.find_by!(email: "foo")
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."email" = 'foo' LIMIT 1
ActiveRecord::RecordNotFound: ActiveRecord::RecordNotFound
```

**Comment by ta1kt0me** [comment]
find_by は unique と組み合わせて使うケース

**Comment by ta1kt0me** [comment]
reloadしてもobject_id変わらない
```rb
irb(main):046:0> user.object_id
=> 70325978542080
irb(main):047:0> user.reload.object_id
=> 70325978542080
```

**Comment by ta1kt0me** [comment]
user.emailの値を再取得したいから、この例だとuser.email.reloadの方が分かりやすくないだろうか

**Comment by yutackall** [comment]
Rails 4 の AR#update
http://qiita.com/tanaka51/items/dfe1ae1a81dab6ebd3c2

**Comment by ta1kt0me** [comment]
`update_attributes`,`update_attribute`はsave+reloadの動きをする

**Comment by ta1kt0me** [comment]
update_attributeはvalidationが働かない、危険 :bomb:

**Comment by yutackall** [comment]
http://qiita.com/tyamagu2/items/8abd93bb7ab0424cf084

**Comment by hashcc** [comment]
こんな、updateメソッドあるの・・

**Comment by ta1kt0me** [comment]
クラスメソッドのupdateなんてあったんだ。。。。

**Comment by ta1kt0me** [comment]
RecordNotFound発生しても、途中までcommitしちゃう。
```rb
User.update([1,2,3],[{email: "2@example.com"}])
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
   (0.2ms)  begin transaction
  SQL (0.3ms)  UPDATE "users" SET "email" = ?, "updated_at" = ? WHERE "users"."id" = 1  [["email", "2@example.com"], ["updated_at", Mon, 06 Apr 2015 12:25:49 UTC +00:00]]
   (1.6ms)  commit transaction
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 2]]
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 3]]
ActiveRecord::RecordNotFound: Couldn't find User with id=3
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:198:in `raise_record_not_found_exception!'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:284:in `find_one'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:268:in `find_with_ids'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:35:in `find'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:122:in `find'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:334:in `update'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:332:in `block in update'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:332:in `map'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:332:in `with_index'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:332:in `update'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.2/lib/active_record/querying.rb:7:in `update'
	from (irb):54
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
	from /Users/toku/.ghq/github.com/ta1kt0me/sample_app_ycyc/vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'irb(main):055:0>
irb(main):056:0*
irb(main):057:0* User.first
  User Load (0.3ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT 1
=> #<User id: 1, name: "The Dude", email: "2@example.com", created_at: "2015-04-06 11:58:39", updated_at: "2015-04-06 12:25:49">
```

**Comment by ta1kt0me** [comment]
しかも、1件1件selectとしてupdate

**Comment by ta1kt0me** [comment]
nullをDBを許容するかどうかという話をしている

**Comment by ta1kt0me** [comment]
close ボタンの位置が悪いという話をしている

**Comment by ta1kt0me** [comment]
6.2ユーザーを検証する の前まで

**Comment by yucao24hours** [comment]
> close ボタンの位置がクソという話をしている
