### ISSUE TITLE
keekeekee 5t111111 ManabuSeki

### ISSUE THREAD

**Issue by ManabuSeki** [yochiyochirb/meetups#974]
6.2.2プレゼンスを検証する から

**Comment by ManabuSeki** [comment]
hi

**Comment by 5t111111** [comment]
hi

**Comment by 5t111111** [comment]
テスト駆動開発を慎重に進めることは、結局は「私たちが正しい事項をテストしている」という自信を得る為の唯一の方法なのです。

**Comment by ManabuSeki** [comment]
```
irb(main):003:0* user.save
   (0.1ms)  SAVEPOINT active_record_1
   (0.1ms)  ROLLBACK TO SAVEPOINT active_record_1
=> false
irb(main):004:0> !
irb(main):005:0* user.save!
   (0.1ms)  SAVEPOINT active_record_1
   (0.1ms)  ROLLBACK TO SAVEPOINT active_record_1
ActiveRecord::RecordInvalid: Validation failed: Name can't be blank
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/validations.rb:57:in `save!'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/transactions.rb:275:in `block in save!'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/transactions.rb:330:in `block in with_transaction_returning_status'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:221:in `within_new_transaction'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/transactions.rb:209:in `transaction'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/transactions.rb:327:in `with_transaction_returning_status'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/transactions.rb:275:in `save!'
	from (irb):5
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/sekimanabu/work/yochiyochirb_tutorial/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):006:0> user.valid?
=> false
```

**Comment by kiyamatic** [comment]
user.valid? = saveしないで検証してくれる

**Comment by ManabuSeki** [comment]
```
あるオブジェクトが、真偽値を返すfoo?というメソッドに応答するのであれば、それに対応するbe_fooというテストメソッドが (自動的に) 存在します。
```
さらっとすごいこと書いてる

**Comment by kiyamatic** [comment]
rspec難しいな

**Comment by 5t111111** [comment]
6.2.2まで終わり。

**Comment by kiyamatic** [comment]
英語も勉強しないとダメだな・・・
